// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Generates an ambient soundscape that matches the day/night toggle.
 *
 * - generateAmbientSoundscape - A function that generates an ambient soundscape based on the time of day.
 * - GenerateAmbientSoundscapeInput - The input type for the generateAmbientSoundscape function.
 * - GenerateAmbientSoundscapeOutput - The return type for the generateAmbientSoundscape function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import wav from 'wav';

const GenerateAmbientSoundscapeInputSchema = z.object({
  timeOfDay: z
    .enum(['day', 'night'])
    .describe('The time of day (day or night).'),
});
export type GenerateAmbientSoundscapeInput = z.infer<
  typeof GenerateAmbientSoundscapeInputSchema
>;

const GenerateAmbientSoundscapeOutputSchema = z.object({
  media: z.string().describe('The ambient soundscape as a WAV data URI.'),
});
export type GenerateAmbientSoundscapeOutput = z.infer<
  typeof GenerateAmbientSoundscapeOutputSchema
>;

export async function generateAmbientSoundscape(
  input: GenerateAmbientSoundscapeInput
): Promise<GenerateAmbientSoundscapeOutput> {
  return generateAmbientSoundscapeFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateAmbientSoundscapePrompt',
  input: {schema: GenerateAmbientSoundscapeInputSchema},
  output: {schema: GenerateAmbientSoundscapeOutputSchema},
  prompt: `You are an expert sound designer creating ambient soundscapes.

  Create an ambient soundscape for the following time of day: {{timeOfDay}}.

  The soundscape should include rustling, running, and flapping sounds that change and crossfade, giving a vivid sense of environmental presence. Take the time of day into account in the volume, type, number, and frequency of changes of each sound event.

  The final result should be a single string that, when evaluated, is valid PCM audio data encoded in base64.

  IMPORTANT: You MUST generate valid audio data.  Do not include ANY text in your response other than the base64 encoded audio.
  `,
});

const generateAmbientSoundscapeFlow = ai.defineFlow(
  {
    name: 'generateAmbientSoundscapeFlow',
    inputSchema: GenerateAmbientSoundscapeInputSchema,
    outputSchema: GenerateAmbientSoundscapeOutputSchema,
  },
  async input => {
    const query = `Generate ambient soundscape for ${input.timeOfDay}`;
    const {media: pcmMedia} = await ai.generate({
      model: 'googleai/gemini-2.5-flash-preview-tts',
      config: {
        responseModalities: ['AUDIO'],
        speechConfig: {
          voiceConfig: {
            prebuiltVoiceConfig: {voiceName: 'Algenib'},
          },
        },
      },
      prompt: query,
    });
    if (!pcmMedia) {
      throw new Error('no media returned');
    }
    const audioBuffer = Buffer.from(
      pcmMedia.url.substring(pcmMedia.url.indexOf(',') + 1),
      'base64'
    );
    const media = 'data:audio/wav;base64,' + (await toWav(audioBuffer));

    return {media};
  }
);

async function toWav(
  pcmData: Buffer,
  channels = 1,
  rate = 24000,
  sampleWidth = 2
): Promise<string> {
  return new Promise((resolve, reject) => {
    const writer = new wav.Writer({
      channels,
      sampleRate: rate,
      bitDepth: sampleWidth * 8,
    });

    let bufs = [] as any[];
    writer.on('error', reject);
    writer.on('data', function (d) {
      bufs.push(d);
    });
    writer.on('end', function () {
      resolve(Buffer.concat(bufs).toString('base64'));
    });

    writer.write(pcmData);
    writer.end();
  });
}

